shallow_clone: true

environment:
  matrix:
  - COMPILER: VS_2017
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - COMPILER: VS_2017
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - COMPILER: VS_2015
#    ARCHITECTURE: x86
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - COMPILER: VS_2015
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - COMPILER: VS_2013
#    ARCHITECTURE: x86
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#  - COMPILER: VS_2013
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#  - COMPILER: VS_2012
#    ARCHITECTURE: x86
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2012
#  - COMPILER: VS_2012
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2012
#  - COMPILER: VS_2010
#    ARCHITECTURE: x86
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2010
#  - COMPILER: VS_2010
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2010
#  - COMPILER: MINGW_492
#    ARCHITECTURE: x86
#  - COMPILER: MINGW_W64
#    ARCHITECTURE: x64

build:
  verbosity: detailed
  parallel: true

configuration:
  - Debug
  - Release

clone_folder: C:\projects\c-marpaESLIF

matrix:
  fast_finish: true # Immediately finish build once one of the jobs fails

cache:
  - C:\strawberry # Do not reinstall strawberryperl between builds

before_build:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  - cpanm --notest Dist::Zilla
  - cpanm --notest Path::Tiny
  - cpanm --notest Moo Moose MooseX::Role::Parameterized
  - sudo cpanm --notest Archive::Tar Class::Tiny Config::AutoConf::INI ExtUtils::CBuilder ExtUtils::CppGuess ExtUtils::MakeMaker File::Basename File::chdir File::Copy File::Copy::Recursive File::Find File::Path File::Spec File::Temp IPC::Open3 IPC::Run Params::Validate Perl::OSType Role::Tiny Scalar::Util Test::More Test::More::UTF8 Log::Log4perl Log::Any Log::Any::Adapter Log::Any::Adapter::Log4perl Test::EOL Test::Kwalitee Test::NoTabs Test::Pod::Coverage namespace::autoclean
  - cpanm --notest Dist::Zilla::PluginBundle::RJBS
  - pushd src/bindings/perl && dzil authordeps --missing | xargs cpanm --notest && popd

init:
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS_2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS_2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2015" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS_2013" call "%VS120COMNTOOLS%\vsvars32.bat"
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2013" call "%VS120COMNTOOLS%\vsvars64.bat"
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS_2012" call "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" x86
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2012" call "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" x86_amd64
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS_2010" call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS_2010" call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86_amd64
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MINGW_492" set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MINGW_W64" set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - ECHO %PATH%

install:
- cmd: cinst cmake
- cmd: cinst nsis
- cmd: cpanm --notest Dist::Zilla
- cmd: cpanm --notest Path::Tiny
- cmd: cpanm --notest Moose MooseX::Role::Parameterized
- cmd: cpanm --notest Archive::Tar Class::Tiny Config::AutoConf::INI ExtUtils::CBuilder ExtUtils::CppGuess ExtUtils::MakeMaker File::Basename File::chdir File::Copy File::Copy::Recursive File::Find File::Path File::Spec File::Temp IPC::Open3 IPC::Run Params::Validate Perl::OSType Role::Tiny Scalar::Util Test::More Test::More::UTF8 Log::Log4perl Log::Any Log::Any::Adapter Log::Any::Adapter::Log4perl Test::EOL Test::Kwalitee Test::NoTabs Test::Pod::Coverage
- cmd: cpanm --notest Dist::Zilla::PluginBundle::RJBS
- cmd: pushd src/bindings/perl && dzil authordeps --missing | xargs cpanm --notest && popd

build_script:
  - cd C:\projects\c-marpaESLIF
  - perl CMakeObjects.PL
  - del /f /s /q output
  - cmake -G "NMake Makefiles" -DALL_IN_ONE=TRUE .
  - nmake

test_script:
  - nmake check
  - nmake install
  - nmake pack
