#
# travis
#
language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
# We want to try perl standalone first
  - sudo apt-get update
  - sudo apt-get install cpanminus
  - sudo cpanm --notest Archive::Tar Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy::Recursive IPC::Run Perl::OSType
  - perl CMakeObjects.PL
  - rm -rf output
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
  - sh ./install-c-genericLogger.sh
  - cmake .
script:
  - make check
  - sudo make install
  - tconv -f ASCII -t UTF-16 -o output/lib/tconv.tconv-UTF-16.c src/tconv.c
  - iconv -f ASCII -t UTF-16 -o output/lib/tconv.iconv-UTF-16.c src/tconv.c
  - uconv -f ASCII -t UTF-16 -o output/lib/tconv.uconv-UTF-16.c src/tconv.c
  - ls -l src/tconv.c output/lib/tconv.iconv-UTF-16.c output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - file src/tconv.c output/lib/tconv.iconv-UTF-16.c output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - diff output/lib/tconv.iconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - diff output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - tconv -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
