language: c
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sudo apt-get update
  - sudo apt-get install cpanminus
  - sudo cpanm Archive::Tar Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy File::Copy::Recursive IPC::Run Perl::OSType
  - perl CMakeObjects.PL
  - rm -rf output
  - sudo cpanm Dist::Zilla Dist::Zilla::PluginBundle::RJBS
  - dzil authordeps --missing | xargs sudo cpanm
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles pcre2
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
  - sh ./install-c-marpaWrapper.sh
  - sh ./install-c-tconv.sh
  - cmake .
script:
  - make
  - make check
#  - ./output/lib/marpaESLIFTester
#  - ./output/lib/adventTester
#  - ./output/lib/russellParadoxTester
#  - ./output/lib/jsonTester
#  - ./output/lib/selfTester
  - sudo make package
  - sudo make install
