language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sh ./install-c-genericLogger.sh
  - cmake .
script:
  - make check
  - file src/tconv.c output/lib/tconv.UTF-16.c
  - sudo make install