language: c
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
  - sh ./install-c-marpaWrapper.sh
  - sh ./install-c-tconv.sh
  - cmake .
script:
  - make
  - make check
#  - ./output/lib/marpaESLIFTester
#  - ./output/lib/adventTester
#  - ./output/lib/russellParadoxTester
#  - ./output/lib/jsonTester
#  - ./output/lib/selfTester
  - sudo make package
  - sudo make install
