language: c
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sudo apt-get update
  - sudo apt-get install cpanminus
# Standard Dist::Zilla, this will install a bunch of prereqs, speeding up the upgrade
  - sudo apt-get install libdist-zilla-perl
# Upgrade Dist::Zilla
  - sudo cpanm --notest Dist::Zilla
# This is not in the prereqs it seems, but the latest MooseX::Role::Parameterized is highly recommended -; let's do it for Moose as well
  - sudo cpanm --notest Moose MooseX::Role::Parameterized
# For my scripts
  - sudo cpanm --notest Archive::Tar Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy File::Copy::Recursive IPC::Run Perl::OSType
  - perl CMakeObjects.PL
  - rm -rf output
  - sudo cpanm --notest Dist::Zilla::PluginBundle::RJBS
  - dzil authordeps --missing | xargs sudo cpanm --notest
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles pcre2
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
  - sh ./install-c-marpaWrapper.sh
  - sh ./install-c-tconv.sh
  - cmake .
script:
  - make
  - make check
#  - ./output/lib/marpaESLIFTester
#  - ./output/lib/adventTester
#  - ./output/lib/russellParadoxTester
#  - ./output/lib/jsonTester
#  - ./output/lib/selfTester
  - sudo make package
  - sudo make install
