language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - "cmake --version"
  - cmake .
script:
  - make check && make check && make install
