language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sudo add-apt-repository -y ppa:teward/icu-backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev
  - sh ./install-c-genericLogger.sh
  - sudo ldconfig /usr/local/lib
  - cmake .
script:
  - make VERBOSE=1
  - ldd output/lib/libtconv.so.1.0.0
  - make check VERBOSE=1
  - sudo make install
