language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sh ./install-c-genericLogger.sh
  - cmake .
script:
  - make
  - LD_LIBRARY_FLAGS=${LD_LIBRARY_FLAGS}:/usr/local/lib:`icu-config --ldflags-searchpath` make check && sudo make install
