language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sh ./install-c-genericLogger.sh
  - sudo ldconfig /usr/local/lib
  - cmake .
script:
  - make VERBOSE=1
  - make check VERBOSE=1
  - sudo make install
