language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sh ./install-c-genericLogger.sh
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cmake .
script:
  - make VERBOSE=1
  - ldd output/lib/libtconv.so.1.0.0
  - make check VERBOSE=1
  - sudo make install
